### ISSUE TITLE
unable to build 

### ISSUE THREAD

**Issue by Amateur-God** [Tenpi/Moebooru.moe#6]
```
[webpack-cli] Failed to load '/opt/moebooru/webpack.config.js' config
[webpack-cli] /opt/moebooru/node_modules/css-minimizer-webpack-plugin/node_modules/jest-worker/build/index.js:109
      enableWorkerThreads: this._options.enableWorkerThreads ?? false,
                                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/moebooru/node_modules/css-minimizer-webpack-plugin/dist/index.js:17:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by Tenpi** [comment]
Node.js version too old. I can confirm that it works on latest stable (v20.11.1) it was my mistake for not updating the readme and keeping it on an old version.
